services:
  auth-proxy:
    build:
      context: ./AuthProxy
      args:
        - USER=${USER:-user} # Your User Name
        - PASSWORD=${PASSWORD:-Passw0rd!} # Your Password
    image: auth-proxy
    container_name: auth-proxy
    environment:
      - vscode=http://vscode-server:8000 # VSCode URL
      - vscode_map=/ # Mapping VSCode Path
    ports:
      - "8000:80"
    restart: always
  vscode-server:
    build:
      context: ./VSCode
      args:
        - USER=${USER:-user} # Your User Name
        - USER_ID=${USER_ID:-1000} # Your User ID
        - GROUP_ID=${GROUP_ID:-1000} # Your GROUP ID
    image: vscode-server
    container_name: vscode-server
    environment:
      - WORKDIR=${WORKDIR:-WORKDIR} # Work Directory Name
    volumes:
      - type: volume
        source: vscode_data
        target: /home/${USER:-user}/.vscode
      - type: volume
        source: vscode_server_data
        target: /home/${USER:-user}/.vscode-server
      - type: volume
        source: workdir_data
        target: /home/${USER:-user}/${WORKDIR:-WORKDIR}
    working_dir: /home/${USER:-user}/${WORKDIR:-WORKDIR}
    restart: always

volumes:
    vscode_data:
        name: vscode_data
    vscode_server_data:
        name: vscode_server_data
    workdir_data:
        name: workdir_data
