services:
  vscode-server:
    build:
      context: .
      args:
        - USER=${USER:-user} # Your User Name
        - USER_ID=${USER_ID:-1000} # Your User ID
        - GROUP_ID=${GROUP_ID:-1000} # Your GROUP ID
    image: vscode-server
    container_name: vscode-server
    ports:
      - "8000:8000"
